export default {
  LOGIN: "LOGIN",
  ADD_BOOK: "ADD_BOOK",
  GET_ALL_BOOKS: "GET_ALL_BOOKS",
  DELETE_BOOK: "DELETE_BOOK",
  INCREASE_BOOK_COPIES: "INCREASE_BOOK_COPIES",
  DECREASE_BOOK_COPIES: "DECREASE_BOOK_COPIES",
  ISSUE_BOOK: "ISSUE_BOOK",
  FILTER_BOOKS: "FILTER_BOOKS",
  LOGOUT: "LOGOUT",
  REGISTER: "REGISTER",
};
